---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: keycloak

releases:
- name: keycloak-boshrelease
  version: latest
- sha1: e88a0e03dac65f64ef743f0244a972722edadb2b
  url: https://s3.eu-central-1.amazonaws.com/postgresql-tde-boshrelease-pipeline-ev/osb-bosh-postgresql-tde-0.3.6.tgz
  name: osb-bosh-postgresql-tde
  version: 0.3.6

variables:
- name: admin_credentials
  type: user
  options:
    username: admin
- name: postgresql_credentials
  type: user
  options:
    username: keycloak
- name: backup_credentials
  type: user
  options:
    username: backup
- name: exporter_credentials
  type: user
  options:
    username: exporter
- name: replicationPassword
  type: password


update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: postgresql
  instances: 1
  vm_type: minimal
  stemcell: default  
  networks:
  - name: default
  azs:
  - z1
  persistent_disk_type: 10GB
  jobs:
  - name: postgres
    release: osb-bosh-postgresql-tde
    provides: 
      postgres:
        aliases:
        - domain: postgres.keycloak
  - name: backup-agent
    release: osb-bosh-postgresql-tde
  properties:
    backup_agent:
      username: ((backup_credentials.username))
      password: ((backup_credentials.password))
    postgres_exporter:
      user: ((exporter_credentials.username))
      password: ((exporter_credentials.password))
      port: 5432
    postgres:
      tde:
        key: 882fb7c12e80280fd664c69d2d636913
      ssl:
        enabled: true
        ca: ((/bosh-test/osb/elasticsearch/ca.certificate))((/bosh-test/osb/elasticsearch/ca.ca))
        cakey: ((/bosh-test/osb/elasticsearch/ca.private_key))
        alternativenames:
        - "DNS:postgres.keycloak"
      replication:
        archive_mode: 'on'
        enabled: true
      resource:
        shared_buffers: 128MB
        temp_buffers: 8MB
      encoding:
        lc_messages: 'en_US.UTF-8'
        lc_monetary: 'en_US.UTF-8'
        lc_numeric:  'en_US.UTF-8'
        lc_time:     'en_US.UTF-8'
      config:
        port: 5432
        max_connections: 400
        max_fiLes_per_process: 1000
        shared_preload_libraries: 'pg_stat_statements'
      archive_cleanup: 
        threshold: 10
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      admin_users:
      - username: ((exporter_credentials.username))
        password: ((exporter_credentials.password))
        admin: false
      backup_users:
      - username: ((backup_credentials.username))
        password: ((backup_credentials.password))
      users:
      - username: ((postgresql_credentials.username))
        password: ((postgresql_credentials.password))
        admin: true
      databases:
      - name: keycloak
        users:
        - ((postgresql_credentials.username))
        extensions: 
        - citext 
      - name: admin
        users:
        - pgpool_health
- name: keycloak
  instances: 2
  vm_type: minimal
  stemcell: default  

  networks:
  - name: default
  azs:
  - z2
  - z3
  persistent_disk_type: 10GB
  jobs:
  - name: keycloak
    release: keycloak-boshrelease
  properties:
    keycloak:
      cluster:
        method: tcpping
      admin:
        user: ((admin_credentials.username))
        password: ((admin_credentials.password))
      database:
        host: postgres.keycloak
        password: ((postgresql_credentials.password))
        user: ((postgresql_credentials.username))
        name: keycloak
        append: "?sslmode=verify-full&sslfactory= org.postgresql.ssl.DefaultJavaSSLFactory"
