---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: keycloak

releases:
- name: keycloak-boshrelease
  version: latest

variables:
- name: admin_credentials
  type: user
  options:
    username: admin

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: keycloak
  instances: 1
  vm_type: minimal
  stemcell: default  
  networks:
  - name: default
  azs:
  - z3
  - z2
  - z1
  persistent_disk: 0
  jobs:
  - name: keycloak
    release: keycloak-boshrelease
  properties:
    keycloak:
      admin:
        user: ((admin_credentials.username))
        password: ((admin_credentials.password))
